#
# prep the servers for doing fun stuff :-)
#

- set_fact:
    myvars: "{{ servervars[inventory_hostname] }}"

- name: distribute the cluster hosts file
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK cluster hosts"
    block: "{{ lookup('file', '{{ inventory_dir }}/files/hosts') }}"
  become: true

- name: add repositories for NetQ/HostPack, Mesosphere, Docker and then update the apt cache
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: A88BBC95
  become: true
- apt_repository:
    repo: deb [arch=amd64] https://apps3.cumulusnetworks.com/repos/deb xenial netq-1.2
    filename: netq
    state: present
  become: true
- apt_key:
    keyserver: keyserver.ubuntu.com
    id: E56151BF
  become: true
- apt_repository:
    repo: deb http://repos.mesosphere.io/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main
    filename: mesosphere
    state: present
  become: true
- apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
- apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  become: true
- apt:
    update_cache: yes
  become: true


- name: install useful operational packages
  apt:
    name: "{{ item }}"
  become: true
  with_items:
  - zile
  - lldpd
  - traceroute
  - ifupdown
  - tcpdump
  - ethtool
- service:
    name: lldpd
    enabled: yes
    state: started
  become: true

- name: Add HostPack (NetQ and FRR)
  apt:
    name: cumulus-netq
    state: latest

  become: yes
- copy:
    src: files/frr_3.1+cl3u1_amd64.deb
    dest: "/tmp"
- apt:
    deb: /tmp/frr_3.1+cl3u1_amd64.deb
  become: yes


- name: high speed networking
  command: ifdown --force --allow=ansible
  become: true
  ignore_errors: yes
- blockinfile:
    dest: /etc/network/interfaces
    marker: "# {mark} ANSIBLE MANAGED BLOCK fabric"
    block: |
      auto lo
      allow-ansible lo
      iface lo inet static
        address {{ myvars.V4 }}/32

      auto lo
      allow-ansible lo
      iface lo inet6 static
        address {{ myvars.V6 }}/128

      auto eth1
      allow-ansible eth1
      iface eth1 inet manual

      auto eth2
      allow-ansible eth2
      iface eth2 inet manual
  become: true
- template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: "u=rw,g=r,o=r"
  become: yes
- copy:
    src: "daemons"
    dest: "/etc/frr/daemons"
    owner: frr
    group: frr
    mode: "u=rw,g=r,o=r"
  become: yes
- copy:
    src: 99cumulus_defaults
    dest: /etc/sysctl.d/99cumulus_defaults.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: yes
- command: 'sysctl --system'
  become: yes
- service:
    name: frr
    enabled: yes
    state: restarted
  become: yes
- shell: ifdown --force --all --allow=ansible && ifup --force --all --allow=ansible
  become: true

- name: Start NetQ and Connect to the NetQ Telemetry Server
  service:
    name: rsyslog
    state: restarted
  become: true
- service:
    name: netqd
    enabled: yes
    state: restarted
  become: true
- copy:
    src: files/netq.yml
    dest: "/etc/netq/netq.yml"
    owner: root
    group: root
    mode: "u=rw,o=r,g=r"
  become: yes
- pause:
    seconds: 5
- shell: netq config restart agent
