---
- hosts: leafs

  tasks:

  - name:  set the host specific vars and default UPLINK_PORTS facts
    set_fact:
      myvars: "{{ switchvars[inventory_hostname] }}"
      UPLINK_PORTS: '{{ WIDE_UPLINKS }}'
  - name:  change the PEER_PORTS for mellanox switches
    set_fact:
      UPLINK_PORTS: '{{ NARO_UPLINKS }}'
    when: ansible_cmdline.cl_platform == "mlnx_x86_MSN2100"


  - name: Make ourselves unattractive from a BGP perspective (route to our peer)
    nclu:
      commands:
      - add routing route-map MAINT permit 10 set as-path prepend {{ myvars.ASN }}
      - add routing route-map MAINT permit 11 set as-path prepend {{ myvars.ASN }}
      - add bgp neighbor {{ UPLINK_PORTS }} route-map MAINT out
      atomic: true
      description: Make Routing Ugly
  - pause:
      seconds: 20

  - name: Become the CLAG secondary
    nclu:
      commands:
      - add interface peerlink.4094 clag priority 3000
      atomic: true
      description: Become CLAG secondary
  - pause:
      seconds: 10


  - name: Kill the access MLAGs
    nclu:
      commands:
      - add bond access-mlag-{{ item.0 + 1 }} link down
      atomic: true
      description: "link down on the server access interfaces"
    with_indexed_items: "{{ ACCESS.split(',') }}"
  - pause:
      seconds: 10


  - name: Initiate ONIE install
    shell: "/usr/cumulus/bin/onie-select -if"
    become: true
  - shell: nohup bash -c 'sleep 2 && shutdown -r now "Ansible kernel update applied"' &
    become: true
    async: 1
    poll: 0
    ignore_errors: true
...